CREATE TABLE `rooms` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `room_name` varchar(120) DEFAULT NULL,
  `street` varchar(120) DEFAULT NULL,
  `city` varchar(120) DEFAULT NULL,
  `number` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `room_name` (`room_name`)
) ENGINE=InnoDB AUTO_INCREMENT=364 DEFAULT CHARSET=latin1;

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) DEFAULT NULL,
  `password` varchar(512) DEFAULT NULL,
  `name` varchar(120) DEFAULT NULL,
  `surname` varchar(120) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;


insert into rooms (id, room_name, city, street, number) values(1,"ExitRoom ™", "Gliwice", "Łąkowa", "111");
insert into rooms (id, room_name, city, street, number) values(2,"LetMeOut", "Bytom", "Niwy", "168");
insert into rooms (id, room_name, city, street, number) values(3,"Logical Room", "Ruda Śląska", "Wręczycka", "171");
insert into rooms (id, room_name, city, street, number) values(4,"Piwnica Quest", "Ruda Śląska", "Ogrodowa", "159");
insert into rooms (id, room_name, city, street, number) values(5,"Room Escape", "Ruda Śląska", "Prusa", "240");
insert into rooms (id, room_name, city, street, number) values(6,"Enigma Room", "Gliwice", "Paproć", "124");
insert into rooms (id, room_name, city, street, number) values(7,"Uwięzieni", "Gliwice", "Zacisze", "159");
insert into rooms (id, room_name, city, street, number) values(8,"Escape Plan", "Katowice", "Harcerska", "114");
insert into rooms (id, room_name, city, street, number) values(9,"Maze Kraków", "Ruda Śląska", "Błękitna", "224");
insert into rooms (id, room_name, city, street, number) values(10,"Tkalnia Zagadek", "Bytom", "Sarenki", "241");
insert into rooms (id, room_name, city, street, number) values(11,"Niepokój", "Bytom", "Widokowa", "116");
insert into rooms (id, room_name, city, street, number) values(12,"Survival Room Open The Lock", "Gliwice", "Garncarska", "129");
insert into rooms (id, room_name, city, street, number) values(13,"Mysterious Room", "Bytom", "Kasztanowa", "250");
insert into rooms (id, room_name, city, street, number) values(14,"Zamknieciwpokoju.pl", "Ruda Śląska", "Łęgi", "42");
insert into rooms (id, room_name, city, street, number) values(15,"Spaced-out", "Kraków", "Okrężna", "45");
insert into rooms (id, room_name, city, street, number) values(16,"HURRY UP", "Katowice", "Rolnicza", "227");
insert into rooms (id, room_name, city, street, number) values(17,"Wyjście Awaryjne", "Katowice", "Mesyńska", "31");
insert into rooms (id, room_name, city, street, number) values(18,"Break The Code", "Bytom", "Okulickiego", "140");
insert into rooms (id, room_name, city, street, number) values(19,"WALKOUT", "Gliwice", "Piękna", "181");
insert into rooms (id, room_name, city, street, number) values(20,"Questrooms", "Kraków", "Spółdzielcza", "114");
insert into rooms (id, room_name, city, street, number) values(21,"High Grade IS", "Bytom", "Cegielniana", "118");
insert into rooms (id, room_name, city, street, number) values(22,"Praski Pokój Zagadek", "Gliwice", "Słoneczna", "245");
insert into rooms (id, room_name, city, street, number) values(23,"Montownia Zagadek", "Kraków", "Górna", "155");
insert into rooms (id, room_name, city, street, number) values(24,"Enigmat Escape", "Kraków", "Konstytucji 3 Maja", "168");
insert into rooms (id, room_name, city, street, number) values(25,"Horror escape room", "Bytom", "Burszki", "28");
insert into rooms (id, room_name, city, street, number) values(26,"Secret Room - Brain Code", "Kraków", "Słoneczna", "6");
insert into rooms (id, room_name, city, street, number) values(27,"Dragon Escape Room", "Gliwice", "Pilotów", "224");
insert into rooms (id, room_name, city, street, number) values(28,"Splot Zagadek", "Kraków", "Sienkiewicza", "83");
insert into rooms (id, room_name, city, street, number) values(29,"LOST ROOM", "Kraków", "Tytanowa", "71");
insert into rooms (id, room_name, city, street, number) values(30,"Break The Brain", "Katowice", "Kręta", "15");
insert into rooms (id, room_name, city, street, number) values(31,"Escape Land Kraków", "Bytom", "Kościuszki", "235");
insert into rooms (id, room_name, city, street, number) values(32,"ZAGWOZDKA", "Bytom", "Diany", "85");
insert into rooms (id, room_name, city, street, number) values(33,"Escape Factory", "Gliwice", "Orzechowa", "246");
insert into rooms (id, room_name, city, street, number) values(34,"Dom Kluczy", "Bytom", "Stawowa", "98");
insert into rooms (id, room_name, city, street, number) values(35,"Quest Room", "Katowice", "Rzeszowskiego", "64");
insert into rooms (id, room_name, city, street, number) values(36,"In the Room", "Kraków", "Admiralska", "252");
insert into rooms (id, room_name, city, street, number) values(37,"Great Escape", "Gliwice", "Żeromskiego", "223");
insert into rooms (id, room_name, city, street, number) values(38,"Trapped", "Kraków", "Witosa", "9");
insert into rooms (id, room_name, city, street, number) values(39,"TheGame", "Bytom", "Heweliusza", "96");
insert into rooms (id, room_name, city, street, number) values(40,"Mystery Rooms", "Bytom", "Sportowa", "157");
insert into rooms (id, room_name, city, street, number) values(41,"Outscape", "Gliwice", "Wolności", "179");
insert into rooms (id, room_name, city, street, number) values(42,"Quest Hunt", "Bytom", "Pod Lasem", "4");
insert into rooms (id, room_name, city, street, number) values(43,"Quest Cage", "Gliwice", "Dolomitowa", "85");
insert into rooms (id, room_name, city, street, number) values(44,"Escape Room Tczew", "Kraków", "Grunwaldzka", "169");
insert into rooms (id, room_name, city, street, number) values(45,"No Escape", "Kraków", "Błotna", "172");
insert into rooms (id, room_name, city, street, number) values(46,"Logic Room - Escape Room Białystok", "Kraków", "Pod Sosnami", "209");
insert into rooms (id, room_name, city, street, number) values(47,"FindOut", "Ruda Śląska", "Dolna", "127");
insert into rooms (id, room_name, city, street, number) values(48,"Dom Zagadek", "Katowice", "Kazimierza Wielkiego", "30");
insert into rooms (id, room_name, city, street, number) values(49,"Escape Koszalin", "Katowice", "Orzeszkowej", "94");
insert into rooms (id, room_name, city, street, number) values(50,"Escape Challenge", "Bytom", "Krótka", "179");
insert into rooms (id, room_name, city, street, number) values(51,"TrapRooms", "Katowice", "Zachodnia", "143");
insert into rooms (id, room_name, city, street, number) values(52,"BUNKER ESCAPE", "Katowice", "Szkolna", "51");
insert into rooms (id, room_name, city, street, number) values(53,"Be Free 45", "Katowice", "Olszynowa", "28");
insert into rooms (id, room_name, city, street, number) values(54,"Set Me Free", "Kraków", "Lisia", "228");
insert into rooms (id, room_name, city, street, number) values(55,"EXITchampions", "Katowice", "Kwiatowa", "123");
insert into rooms (id, room_name, city, street, number) values(56,"Escape Room Szczecin", "Kraków", "Polna", "245");
insert into rooms (id, room_name, city, street, number) values(57,"Combinator Kraków", "Bytom", "Jaskółek", "78");
insert into rooms (id, room_name, city, street, number) values(58,"Pod Kluczem", "Katowice", "Wiewiórcza", "152");
insert into rooms (id, room_name, city, street, number) values(59,"House Escape", "Gliwice", "Strykowska", "232");
insert into rooms (id, room_name, city, street, number) values(60,"SherLOCK Wadowice", "Ruda Śląska", "Ulatowskiego", "82");
insert into rooms (id, room_name, city, street, number) values(61,"REAL ESCAPE KRAKÓW", "Katowice", "Eichendorffa", "105");
insert into rooms (id, room_name, city, street, number) values(62,"No Way Out", "Katowice", "Gorzelniana", "122");
insert into rooms (id, room_name, city, street, number) values(63,"Exit Plan", "Gliwice", "Sosnowe", "144");
insert into rooms (id, room_name, city, street, number) values(64,"Akcja Ewakuacja nr 1 Warszawa", "Katowice", "Grażyńskiego", "100");
insert into rooms (id, room_name, city, street, number) values(65,"Twierdza Pełna Szyfrów Łódź", "Ruda Śląska", "Kątecka", "59");
insert into rooms (id, room_name, city, street, number) values(66,"Komnata Tajemnic", "Ruda Śląska", "Lutego", "236");
insert into rooms (id, room_name, city, street, number) values(67,"Time 4 Secrets", "Kraków", "Akacjowa", "10");
insert into rooms (id, room_name, city, street, number) values(68,"Team Escape", "Ruda Śląska", "Jagiellończyka", "4");
insert into rooms (id, room_name, city, street, number) values(69,"Let's Play The Game", "Kraków", "Podlaska", "157");
insert into rooms (id, room_name, city, street, number) values(70,"Mr Escape", "Ruda Śląska", "Lawendowa", "22");
insert into rooms (id, room_name, city, street, number) values(71,"Exit19.pl", "Katowice", "Rondo Franciszkańskie", "162");
insert into rooms (id, room_name, city, street, number) values(72,"Black Cat Escape Room", "Bytom", "Zachodnia", "42");
insert into rooms (id, room_name, city, street, number) values(73,"Gamescape", "Bytom", "Grunwaldzka", "216");
insert into rooms (id, room_name, city, street, number) values(74,"Key To Be Free", "Kraków", "Niezapominajki", "159");
insert into rooms (id, room_name, city, street, number) values(75,"Panic Room", "Katowice", "Glabisza", "82");
insert into rooms (id, room_name, city, street, number) values(76,"OPEN THE DOOR", "Gliwice", "Tęczowa", "49");
insert into rooms (id, room_name, city, street, number) values(77,"Open The Lock", "Kraków", "Rycerska", "234");
insert into rooms (id, room_name, city, street, number) values(78,"Zamek Międzylesie", "Bytom", "Asnyka", "243");
insert into rooms (id, room_name, city, street, number) values(79,"FearEscape", "Ruda Śląska", "Przy Torze", "28");
insert into rooms (id, room_name, city, street, number) values(80,"EXODUS", "Kraków", "Leśna", "45");
insert into rooms (id, room_name, city, street, number) values(81,"Quest", "Ruda Śląska", "Pod Groniem", "59");
insert into rooms (id, room_name, city, street, number) values(82,"Dark House", "Katowice", "Rzeszowska", "197");
insert into rooms (id, room_name, city, street, number) values(83,"Enigma Rescue", "Bytom", "Zorzy", "72");
insert into rooms (id, room_name, city, street, number) values(84,"Escape Game Warszawa Stare Miasto", "Bytom", "Brynicka", "48");
insert into rooms (id, room_name, city, street, number) values(85,"Folwark Szyfrów", "Gliwice", "Frezerów", "256");
insert into rooms (id, room_name, city, street, number) values(86,"ESCapada", "Katowice", "Findysza", "106");
insert into rooms (id, room_name, city, street, number) values(87,"Mystery House", "Bytom", "Konwaliowa", "203");
insert into rooms (id, room_name, city, street, number) values(88,"LOCKED Escape Room Piła", "Gliwice", "Łęgowa", "122");
insert into rooms (id, room_name, city, street, number) values(89,"KOD - kiedy otworzysz drzwi", "Katowice", "Struga", "143");
insert into rooms (id, room_name, city, street, number) values(90,"ESC HOUSE", "Kraków", "Szara", "256");
insert into rooms (id, room_name, city, street, number) values(91,"World Escape", "Ruda Śląska", "Krzemowa", "237");
insert into rooms (id, room_name, city, street, number) values(92,"The Bunkier Escape Rooms", "Kraków", "Mostowa", "34");
insert into rooms (id, room_name, city, street, number) values(93,"Zagadkownia", "Bytom", "Piłsudskiego", "80");
insert into rooms (id, room_name, city, street, number) values(94,"Zakluczeni.pl", "Kraków", "Klonowa", "237");
insert into rooms (id, room_name, city, street, number) values(95,"Sekretny Pokój", "Gliwice", "Mała", "93");
insert into rooms (id, room_name, city, street, number) values(96,"Twierdza Tajemnic", "Ruda Śląska", "Spacerowa", "115");
insert into rooms (id, room_name, city, street, number) values(97,"Zespół Pałacowo-Hotelowy Jedlinka", "Bytom", "Ptasia", "125");
insert into rooms (id, room_name, city, street, number) values(98,"You're the key", "Katowice", "Krótka", "18");
insert into rooms (id, room_name, city, street, number) values(99,"Share_Lock", "Kraków", "Słowików", "250");
insert into rooms (id, room_name, city, street, number) values(100,"Muzeum Archeologiczno-Historyczne Stargard", "Katowice", "Ślusarska", "77");
insert into rooms (id, room_name, city, street, number) values(101,"Exitmania Escape Room Rzeszów", "Katowice", "Kościuszki", "210");
insert into rooms (id, room_name, city, street, number) values(102,"45 minut", "Ruda Śląska", "Rudzka", "207");
insert into rooms (id, room_name, city, street, number) values(103,"Escape Time", "Gliwice", "Modrzewiowa", "200");
insert into rooms (id, room_name, city, street, number) values(104,"Składnica Szyfrów", "Katowice", "Młodzianowska", "91");
insert into rooms (id, room_name, city, street, number) values(105,"Lock & Roll", "Kraków", "Dobra", "43");
insert into rooms (id, room_name, city, street, number) values(106,"ENIGMA", "Bytom", "Kolejowa", "215");
insert into rooms (id, room_name, city, street, number) values(107,"ESC Room", "Kraków", "Borówkowa", "182");
insert into rooms (id, room_name, city, street, number) values(108,"BlackOut", "Bytom", "Kwiatowa", "55");
insert into rooms (id, room_name, city, street, number) values(109,"The Grand Escape - Escape Room Wałbrzych", "Kraków", "Kryształowa", "202");
insert into rooms (id, room_name, city, street, number) values(110,"Ewakuacja", "Gliwice", "Gdańska", "220");
insert into rooms (id, room_name, city, street, number) values(111,"kryptotex.pl", "Gliwice", "Tischnera", "163");
insert into rooms (id, room_name, city, street, number) values(112,"Unlock the door", "Kraków", "Koszykarska", "216");
insert into rooms (id, room_name, city, street, number) values(113,"No Exit Room Katowice", "Gliwice", "Barbary", "31");
insert into rooms (id, room_name, city, street, number) values(114,"Game Of Locks", "Gliwice", "Sienkiewicza", "121");
insert into rooms (id, room_name, city, street, number) values(115,"SzyfroGRAm", "Ruda Śląska", "Sosnowa", "42");
insert into rooms (id, room_name, city, street, number) values(116,"Weź uciekaj", "Katowice", "Olimpijska", "215");
insert into rooms (id, room_name, city, street, number) values(117,"Plan B", "Gliwice", "Władysława Jagiełły", "179");
insert into rooms (id, room_name, city, street, number) values(118,"Escape Room Majdańska 18 Warszawa", "Kraków", "Kluczborska", "0");
insert into rooms (id, room_name, city, street, number) values(119,"SHOW ESCAPE", "Katowice", "Szkolna", "180");
insert into rooms (id, room_name, city, street, number) values(120,"Escape Me", "Bytom", "Polna", "252");
insert into rooms (id, room_name, city, street, number) values(121,"Intrigue Escape Room", "Kraków", "Kościuszki", "221");
insert into rooms (id, room_name, city, street, number) values(122,"Archiwum Kryminalne", "Katowice", "Leśna", "20");
insert into rooms (id, room_name, city, street, number) values(123,"BlackOut Włocławek", "Ruda Śląska", "Żwirowa", "186");
insert into rooms (id, room_name, city, street, number) values(124,"Funny Will Kraków", "Gliwice", "Grabowa", "213");
insert into rooms (id, room_name, city, street, number) values(125,"Szyb Maciej", "Katowice", "Zacisze", "182");
insert into rooms (id, room_name, city, street, number) values(126,"Wejdź i Wyjdź", "Ruda Śląska", "Radosna", "232");
insert into rooms (id, room_name, city, street, number) values(127,"Try To Leave", "Gliwice", "Ogrodowa", "204");
insert into rooms (id, room_name, city, street, number) values(128,"Warsztat Tajemnic", "Katowice", "Osiedle XXX Lecia", "109");
insert into rooms (id, room_name, city, street, number) values(129,"Escapers", "Gliwice", "Zamoście", "65");
insert into rooms (id, room_name, city, street, number) values(130,"TickTack", "Kraków", "Orla", "101");
insert into rooms (id, room_name, city, street, number) values(131,"4Fun Escape Room Nowy Sącz", "Bytom", "Kościelna", "125");
insert into rooms (id, room_name, city, street, number) values(132,"Zamknieci.pl", "Katowice", "Łąkowa", "157");
insert into rooms (id, room_name, city, street, number) values(133,"ShareLocked", "Katowice", "Krośniewicka", "50");
insert into rooms (id, room_name, city, street, number) values(134,"Chata Zagadek", "Kraków", "Mickiewicza", "98");
insert into rooms (id, room_name, city, street, number) values(135,"Komnata Escape Room", "Gliwice", "Grunwaldzka", "246");
insert into rooms (id, room_name, city, street, number) values(136,"Wola Ucieczki", "Ruda Śląska", "Owocowa", "86");
insert into rooms (id, room_name, city, street, number) values(137,"Escape8", "Ruda Śląska", "Osiedle Górnicze", "210");
insert into rooms (id, room_name, city, street, number) values(138,"Space Quest", "Bytom", "Radosna", "8");
insert into rooms (id, room_name, city, street, number) values(139,"Brain Code - Secret Room", "Katowice", "Żurawia", "90");
insert into rooms (id, room_name, city, street, number) values(140,"Maze in Mind", "Gliwice", "Stefana Batorego", "138");
insert into rooms (id, room_name, city, street, number) values(141,"Dom Kłódek", "Ruda Śląska", "Bogusławskiego", "48");
insert into rooms (id, room_name, city, street, number) values(142,"Magnum", "Gliwice", "Szpitalna", "210");
insert into rooms (id, room_name, city, street, number) values(143,"Tajemnice Starej Piekarni", "Bytom", "Bohaterów Westerplatte", "32");
insert into rooms (id, room_name, city, street, number) values(144,"Forest Escape", "Katowice", "Rzeczna", "198");
insert into rooms (id, room_name, city, street, number) values(145,"Amazeing", "Gliwice", "Klonowa", "172");
insert into rooms (id, room_name, city, street, number) values(146,"Escape Room Katowice", "Kraków", "Dąbrowskiego", "147");
insert into rooms (id, room_name, city, street, number) values(147,"Escape House", "Bytom", "Staszica", "191");
insert into rooms (id, room_name, city, street, number) values(148,"Portal Escape Games", "Kraków", "Ogrodowa", "191");
insert into rooms (id, room_name, city, street, number) values(149,"AlcaTraps", "Gliwice", "Garbarniana", "194");
insert into rooms (id, room_name, city, street, number) values(150,"Dom Zagadek Exitus", "Ruda Śląska", "Goździkowa", "124");
insert into rooms (id, room_name, city, street, number) values(151,"Pokoje Tajemnic", "Bytom", "Boczna", "81");
insert into rooms (id, room_name, city, street, number) values(152,"LOST BAR", "Katowice", "Sosnowa", "43");
insert into rooms (id, room_name, city, street, number) values(153,"Podziemna pułapka", "Kraków", "Rybarska", "136");
insert into rooms (id, room_name, city, street, number) values(154,"FunEscape", "Bytom", "Powstańców Wielkopolskich", "54");
insert into rooms (id, room_name, city, street, number) values(155,"Time Of Mysteries", "Katowice", "Energetyków", "129");
insert into rooms (id, room_name, city, street, number) values(156,"Świat Zagadek", "Ruda Śląska", "Bukowa", "250");
insert into rooms (id, room_name, city, street, number) values(157,"It's a Trap", "Kraków", "Na Stoku", "232");
insert into rooms (id, room_name, city, street, number) values(158,"Furia - Centrum Gier Fabularnych", "Ruda Śląska", "Wrzosowa", "168");
insert into rooms (id, room_name, city, street, number) values(159,"Come Come", "Bytom", "Dobra", "44");
insert into rooms (id, room_name, city, street, number) values(160,"iESCAPE", "Ruda Śląska", "Słupska", "80");
insert into rooms (id, room_name, city, street, number) values(161,"Tajemnicze Domostwo", "Bytom", "Malczewskiego", "69");
insert into rooms (id, room_name, city, street, number) values(162,"Can you escape?", "Bytom", "Deszczowa", "197");
insert into rooms (id, room_name, city, street, number) values(163,"Portal Secret", "Gliwice", "Żeromskiego", "30");
insert into rooms (id, room_name, city, street, number) values(164,"Open Your Brain", "Katowice", "Placowa", "110");
insert into rooms (id, room_name, city, street, number) values(165,"Quest Cage Centrum", "Ruda Śląska", "Spacerowa", "89");
insert into rooms (id, room_name, city, street, number) values(166,"Activity Escape Room", "Katowice", "Techniczna", "199");
insert into rooms (id, room_name, city, street, number) values(167,"SCARY HOSTEL KRAKÓW", "Bytom", "Morenowa", "235");
insert into rooms (id, room_name, city, street, number) values(168,"Twardy Orzech", "Katowice", "Leśna", "86");
insert into rooms (id, room_name, city, street, number) values(169,"Dom Zagadka", "Katowice", "Rynek", "64");
insert into rooms (id, room_name, city, street, number) values(170,"Fox O'clock", "Kraków", "Notecka", "45");
insert into rooms (id, room_name, city, street, number) values(171,"Escepcja", "Kraków", "Objazdowa", "59");
insert into rooms (id, room_name, city, street, number) values(172,"Challenge Exit Room", "Gliwice", "Złota Podkowa", "19");
insert into rooms (id, room_name, city, street, number) values(173,"Dom Tajemnic", "Ruda Śląska", "Radosna", "85");
insert into rooms (id, room_name, city, street, number) values(174,"Busters Escape Rooms", "Katowice", "Gliwicka", "0");
insert into rooms (id, room_name, city, street, number) values(175,"Strych", "Katowice", "Brzozowa", "108");
insert into rooms (id, room_name, city, street, number) values(176,"OtoPokojeZagadek", "Katowice", "Świerkowa", "242");
insert into rooms (id, room_name, city, street, number) values(177,"Strefa Zoltar", "Bytom", "Łąkowa", "244");
insert into rooms (id, room_name, city, street, number) values(178,"Liga Odkrywców", "Gliwice", "Cedrowa", "163");
insert into rooms (id, room_name, city, street, number) values(179,"Element", "Bytom", "Bema", "234");
insert into rooms (id, room_name, city, street, number) values(180,"Find The Key", "Ruda Śląska", "Baśniowa", "9");
insert into rooms (id, room_name, city, street, number) values(181,"Łamacz Escape Rooms", "Kraków", "Graniczna", "24");
insert into rooms (id, room_name, city, street, number) values(182,"Pokój Zagadek - Poziom Drugi", "Katowice", "Rodła", "255");
insert into rooms (id, room_name, city, street, number) values(183,"CI OD GIER", "Katowice", "Kopieczki", "124");
insert into rooms (id, room_name, city, street, number) values(184,"LOFTescape", "Gliwice", "Zgodna", "17");
insert into rooms (id, room_name, city, street, number) values(185,"Tarnowitz in the Jar", "Gliwice", "Kaczora", "61");
insert into rooms (id, room_name, city, street, number) values(186,"Fabryka Czasu", "Gliwice", "Chopina", "200");
insert into rooms (id, room_name, city, street, number) values(187,"Enigma Escape Room", "Ruda Śląska", "Urocza", "231");
insert into rooms (id, room_name, city, street, number) values(188,"Scopeout", "Kraków", "Modrzewiowa", "176");
insert into rooms (id, room_name, city, street, number) values(189,"Dom Sekretów", "Gliwice", "Ogrodowa", "221");
insert into rooms (id, room_name, city, street, number) values(190,"Escape Leszno", "Katowice", "Szkolna", "158");
insert into rooms (id, room_name, city, street, number) values(191,"Project Un-Lock", "Katowice", "Rataja", "153");
insert into rooms (id, room_name, city, street, number) values(192,"Wagarownia", "Bytom", "Izoldy", "209");
insert into rooms (id, room_name, city, street, number) values(193,"House Of Crime", "Bytom", "Tęczowa", "256");
insert into rooms (id, room_name, city, street, number) values(194,"Action Escape", "Ruda Śląska", "Południowa", "193");
insert into rooms (id, room_name, city, street, number) values(195,"Friday the 13th", "Gliwice", "Grabskiego", "214");
insert into rooms (id, room_name, city, street, number) values(196,"Instytut Pamięci Narodowej", "Kraków", "Brzozowa", "196");
insert into rooms (id, room_name, city, street, number) values(197,"The Mystery Room", "Ruda Śląska", "Polna", "190");
insert into rooms (id, room_name, city, street, number) values(198,"One Hour", "Gliwice", "Doktora Judyma", "28");
insert into rooms (id, room_name, city, street, number) values(199,"Eskapizm", "Ruda Śląska", "Grechuty", "204");
insert into rooms (id, room_name, city, street, number) values(200,"Odklucz Swój Umysł", "Bytom", "Zaułek Ferdynanda Lassalla", "187");
insert into rooms (id, room_name, city, street, number) values(201,"Fyrtel Zagadek", "Ruda Śląska", "Lawendowa", "166");
insert into rooms (id, room_name, city, street, number) values(202,"Fear Factory", "Bytom", "Sportowa", "232");
insert into rooms (id, room_name, city, street, number) values(203,"DreamScape", "Kraków", "Maja", "242");
insert into rooms (id, room_name, city, street, number) values(204,"Lock House", "Gliwice", "Wiśniowa", "140");
insert into rooms (id, room_name, city, street, number) values(205,"8 Gates Escape Room", "Gliwice", "Żeromskiego", "152");
insert into rooms (id, room_name, city, street, number) values(206,"WydostanSie Escape Rooms", "Bytom", "Krause", "4");
insert into rooms (id, room_name, city, street, number) values(207,"Secreto", "Ruda Śląska", "Kolejowa", "6");
insert into rooms (id, room_name, city, street, number) values(208,"Projekt Fallout", "Gliwice", "Polna", "240");
insert into rooms (id, room_name, city, street, number) values(209,"DO NOT ENTER", "Katowice", "Ładna", "222");
insert into rooms (id, room_name, city, street, number) values(210,"Black Box", "Gliwice", "Tarnowska", "122");
insert into rooms (id, room_name, city, street, number) values(211,"Fun4Brain", "Kraków", "Jesionowa", "252");
insert into rooms (id, room_name, city, street, number) values(212,"Escape Room Konin", "Kraków", "Kościelna", "51");
insert into rooms (id, room_name, city, street, number) values(213,"Zagadkowo", "Gliwice", "Tarnogórska", "63");
insert into rooms (id, room_name, city, street, number) values(214,"Escape Room Kluczbork", "Katowice", "Łysogórska", "216");
insert into rooms (id, room_name, city, street, number) values(215,"Escape 132", "Ruda Śląska", "Trowniki", "168");
insert into rooms (id, room_name, city, street, number) values(216,"Episode", "Ruda Śląska", "Strzelnicza", "95");
insert into rooms (id, room_name, city, street, number) values(217,"Niepewność", "Ruda Śląska", "Wiśniowa", "123");
insert into rooms (id, room_name, city, street, number) values(218,"Mr Lock Escape Room", "Ruda Śląska", "Jarzębinowa", "143");
insert into rooms (id, room_name, city, street, number) values(219,"Lock&Escape", "Kraków", "Rafineryjna", "244");
insert into rooms (id, room_name, city, street, number) values(220,"ROOMBREAKER", "Ruda Śląska", "Łąkowa", "82");
insert into rooms (id, room_name, city, street, number) values(221,"Escape Room 16", "Gliwice", "Mickiewicza", "12");
insert into rooms (id, room_name, city, street, number) values(222,"Młyn Zagadek", "Katowice", "Zachodnia", "107");
insert into rooms (id, room_name, city, street, number) values(223,"Spichlerz Tajemnic", "Bytom", "Strzelecki", "100");
insert into rooms (id, room_name, city, street, number) values(224,"Continuum", "Ruda Śląska", "Kamienna", "243");
insert into rooms (id, room_name, city, street, number) values(225,"Black Rook", "Katowice", "Niemcewicza", "19");
insert into rooms (id, room_name, city, street, number) values(226,"DZIUPLA", "Kraków", "Kościelna", "96");
insert into rooms (id, room_name, city, street, number) values(227,"Escape Room Konin No1", "Gliwice", "Weryhy-Darowskiego", "87");
insert into rooms (id, room_name, city, street, number) values(228,"Manufaktura Zagadek", "Bytom", "Polna", "145");
insert into rooms (id, room_name, city, street, number) values(229,"The Locked Room", "Kraków", "Bursztynowa", "231");
insert into rooms (id, room_name, city, street, number) values(230,"Projekt EXIT", "Katowice", "Działkowa", "71");
insert into rooms (id, room_name, city, street, number) values(231,"Escape Gdańsk", "Ruda Śląska", "Maczka", "169");
insert into rooms (id, room_name, city, street, number) values(232,"Cinema Escape", "Katowice", "Bursztynowa", "125");
insert into rooms (id, room_name, city, street, number) values(233,"We Want Out", "Ruda Śląska", "Jeżynowa", "130");
insert into rooms (id, room_name, city, street, number) values(234,"WakePark Goczałkowice Zdrój", "Gliwice", "Słoneczna", "208");
insert into rooms (id, room_name, city, street, number) values(235,"Mr. Y's Room", "Ruda Śląska", "Dąbrowskiego", "230");
insert into rooms (id, room_name, city, street, number) values(236,"Pałac Krobielowice", "Katowice", "Cegielniana", "145");
insert into rooms (id, room_name, city, street, number) values(237,"Out of The Box", "Kraków", "Konopnickiej", "9");
insert into rooms (id, room_name, city, street, number) values(238,"The Trap", "Gliwice", "Bzów", "50");
insert into rooms (id, room_name, city, street, number) values(239,"Bez Wyjścia", "Kraków", "Szkolna", "204");
insert into rooms (id, room_name, city, street, number) values(240,"Labirynt Zagadek", "Bytom", "Duchnicka", "226");
insert into rooms (id, room_name, city, street, number) values(241,"Escape Room Monster House", "Ruda Śląska", "Złotno", "187");
insert into rooms (id, room_name, city, street, number) values(242,"Fabryka Pomysłów", "Bytom", "Zamenhofa", "49");
insert into rooms (id, room_name, city, street, number) values(243,"Can U Escape?", "Bytom", "Przygraniczna", "156");
insert into rooms (id, room_name, city, street, number) values(244,"Kopalnia Tajemnic", "Katowice", "Jaśminowa", "132");
insert into rooms (id, room_name, city, street, number) values(245,"No Rules Escape Room", "Kraków", "Radlińskie Chałupki", "106");
insert into rooms (id, room_name, city, street, number) values(246,"Escape Room Czacha", "Kraków", "Ciepła", "69");
insert into rooms (id, room_name, city, street, number) values(247,"Exit Now", "Ruda Śląska", "Czarny Las", "115");
insert into rooms (id, room_name, city, street, number) values(248,"Przygodownia", "Katowice", "Witosa", "13");
insert into rooms (id, room_name, city, street, number) values(249,"Spółdzielnia Socjalna Horyzonty Kultury", "Katowice", "Winogronowa", "217");
insert into rooms (id, room_name, city, street, number) values(250,"House of game", "Kraków", "Rycerska", "247");
insert into rooms (id, room_name, city, street, number) values(251,"Gry Tajemnic - escape room / pokoje zagadek", "Bytom", "Szlachecka", "14");
insert into rooms (id, room_name, city, street, number) values(252,"Zorkout Escape Rooms", "Ruda Śląska", "Handlowa", "143");
insert into rooms (id, room_name, city, street, number) values(253,"Whisper", "Ruda Śląska", "Warszawska", "218");
insert into rooms (id, room_name, city, street, number) values(254,"Na zapleczu sklepu z zabawkami", "Gliwice", "Orzeszkowej", "85");
insert into rooms (id, room_name, city, street, number) values(255,"KMK Systems", "Katowice", "Jeżynowa", "205");
insert into rooms (id, room_name, city, street, number) values(256,"Guciów", "Gliwice", "Grodzka", "22");
insert into rooms (id, room_name, city, street, number) values(257,"Pokoje zagadek", "Gliwice", "Padlewskiego", "164");
insert into rooms (id, room_name, city, street, number) values(258,"Piwnica zagadek", "Kraków", "Leśna", "100");
insert into rooms (id, room_name, city, street, number) values(259,"Bermudy Quest", "Kraków", "Spacerowa", "80");
insert into rooms (id, room_name, city, street, number) values(260,"SkillHill", "Gliwice", "Dekutowskiego Zapory", "256");
insert into rooms (id, room_name, city, street, number) values(261,"Pokój 74", "Gliwice", "Krótka", "234");
insert into rooms (id, room_name, city, street, number) values(262,"Osobliwy dom Pana Adama", "Gliwice", "Wędkarska", "142");
insert into rooms (id, room_name, city, street, number) values(263,"Eureka", "Ruda Śląska", "Matejki", "233");
insert into rooms (id, room_name, city, street, number) values(264,"Zagubieni Escape Room", "Katowice", "Słoneczna", "106");
insert into rooms (id, room_name, city, street, number) values(265,"Escape Room BANK", "Gliwice", "Kwiatowa", "99");
insert into rooms (id, room_name, city, street, number) values(266,"Mind Trick", "Gliwice", "Polna", "53");
insert into rooms (id, room_name, city, street, number) values(267,"Malta Escape Room", "Bytom", "Ogrodowa", "50");
insert into rooms (id, room_name, city, street, number) values(268,"Muzeum Regionalne w Kościanie", "Gliwice", "Graniczna", "96");
insert into rooms (id, room_name, city, street, number) values(269,"Warsztatownia", "Kraków", "Kosynierów", "221");
insert into rooms (id, room_name, city, street, number) values(270,"Dom Gier", "Kraków", "Kamyk", "85");
insert into rooms (id, room_name, city, street, number) values(271,"Key of mind", "Gliwice", "Kolonia", "62");
insert into rooms (id, room_name, city, street, number) values(272,"Escape Graal", "Kraków", "Górna", "192");
insert into rooms (id, room_name, city, street, number) values(273,"I-labirynth", "Bytom", "Antyczna", "49");
insert into rooms (id, room_name, city, street, number) values(274,"Lockout", "Katowice", "Świerkowa", "145");
insert into rooms (id, room_name, city, street, number) values(275,"Fundacja Tradycji Miast i Wsi", "Gliwice", "Bratkowa", "9");
insert into rooms (id, room_name, city, street, number) values(276,"Escape Bus", "Kraków", "Pomorska", "217");
insert into rooms (id, room_name, city, street, number) values(277,"LaserCity", "Gliwice", "Wolsztyńska", "210");
insert into rooms (id, room_name, city, street, number) values(278,"Fox Escape", "Ruda Śląska", "Wałbrzyska", "193");
insert into rooms (id, room_name, city, street, number) values(279,"Trap Jungle", "Katowice", "Wronia", "59");
insert into rooms (id, room_name, city, street, number) values(280,"In&Out", "Katowice", "Świerkowa", "50");
insert into rooms (id, room_name, city, street, number) values(281,"Escape Room 24 - Pokoje zagadek - Team Exit", "Gliwice", "Ogrodowa", "2");
insert into rooms (id, room_name, city, street, number) values(282,"Tajemnica Garażu", "Katowice", "Miła", "103");
insert into rooms (id, room_name, city, street, number) values(283,"Uciec", "Ruda Śląska", "Nowowiejska", "31");
insert into rooms (id, room_name, city, street, number) values(284,"Escape Room Krynica", "Gliwice", "Pogodna", "40");
insert into rooms (id, room_name, city, street, number) values(285,"Lucky Lock", "Gliwice", "Jaśminowa", "241");
insert into rooms (id, room_name, city, street, number) values(286,"Horror House Escape Room", "Gliwice", "Handlowa", "225");
insert into rooms (id, room_name, city, street, number) values(287,"Daj Dyla", "Bytom", "Dworska", "190");
insert into rooms (id, room_name, city, street, number) values(288,"Master of Escape", "Ruda Śląska", "Orchidei", "21");
insert into rooms (id, room_name, city, street, number) values(289,"Broken Key", "Bytom", "Zapolskiej", "255");
insert into rooms (id, room_name, city, street, number) values(290,"Imaginarium Poznań Escape Room", "Gliwice", "Grobla", "165");
insert into rooms (id, room_name, city, street, number) values(291,"To nie pokój - Escape Room Koszalin", "Bytom", "Borowikowa", "232");
insert into rooms (id, room_name, city, street, number) values(292,"Go! Escape", "Ruda Śląska", "Jadwigi", "121");
insert into rooms (id, room_name, city, street, number) values(293,"EGO", "Ruda Śląska", "Elsnera", "206");
insert into rooms (id, room_name, city, street, number) values(294,"OUTROOM", "Katowice", "Żwirki i Wigury", "84");
insert into rooms (id, room_name, city, street, number) values(295,"House of Fun", "Katowice", "Poczty Gdańskiej", "210");
insert into rooms (id, room_name, city, street, number) values(296,"Zoom Natury", "Gliwice", "Zawada", "37");
insert into rooms (id, room_name, city, street, number) values(297,"Exciting Escape Room", "Gliwice", "Czyżyków", "185");
insert into rooms (id, room_name, city, street, number) values(298,"The Brain Game - Świebodzice", "Kraków", "Krasickiego", "183");
insert into rooms (id, room_name, city, street, number) values(299,"Lost Rooms", "Ruda Śląska", "Krótka", "177");
insert into rooms (id, room_name, city, street, number) values(300,"Look Around", "Katowice", "Leśna", "227");
insert into rooms (id, room_name, city, street, number) values(301,"Łowcy Tajemnic", "Bytom", "Rzeczna", "182");
insert into rooms (id, room_name, city, street, number) values(302,"Quick Escape Room", "Kraków", "Piaski", "251");
insert into rooms (id, room_name, city, street, number) values(303,"Escape Project", "Bytom", "Krótka", "98");
insert into rooms (id, room_name, city, street, number) values(304,"Piwnice Zagadek Escape Room Sandomierz", "Kraków", "Kręta", "112");
insert into rooms (id, room_name, city, street, number) values(305,"Schron Kierowania Obroną Cywilną", "Bytom", "Złota", "169");
insert into rooms (id, room_name, city, street, number) values(306,"ESCR - Escape Room Brodnica", "Kraków", "Środkowa", "107");
insert into rooms (id, room_name, city, street, number) values(307,"Unlocked", "Ruda Śląska", "Wileńska", "18");
insert into rooms (id, room_name, city, street, number) values(308,"My Escape Pokój Zagadek", "Gliwice", "Taczaka", "45");
insert into rooms (id, room_name, city, street, number) values(309,"Anikino Sp. z o.o.", "Bytom", "Jodłowa", "94");
insert into rooms (id, room_name, city, street, number) values(310,"Escape 105", "Kraków", "Jatkowa", "50");
insert into rooms (id, room_name, city, street, number) values(311,"Pokój Wyzwań", "Kraków", "Szkolna", "73");
insert into rooms (id, room_name, city, street, number) values(312,"Time Out", "Gliwice", "Kościuszki", "128");
insert into rooms (id, room_name, city, street, number) values(313,"Otwórz umysł", "Bytom", "Plac Margaretek", "21");
insert into rooms (id, room_name, city, street, number) values(314,"Escape Room Chełm", "Ruda Śląska", "Młodej Polski", "52");
insert into rooms (id, room_name, city, street, number) values(315,"Skaut Escape Room", "Katowice", "Boisko Kolejowe", "149");
insert into rooms (id, room_name, city, street, number) values(316,"Creepy Story", "Gliwice", "Szeroka", "151");
insert into rooms (id, room_name, city, street, number) values(317,"Escape Room Dębica", "Bytom", "Sienkiewicza", "74");
insert into rooms (id, room_name, city, street, number) values(318,"The Basement Escape Room", "Bytom", "Paderewskiego", "136");
insert into rooms (id, room_name, city, street, number) values(319,"Ucieknij.PL", "Ruda Śląska", "Graniczka", "185");
insert into rooms (id, room_name, city, street, number) values(320,"Locked Houses", "Bytom", "Władysława Łokietka", "128");
insert into rooms (id, room_name, city, street, number) values(321,"Escape House Elbląg", "Katowice", "Zwycięstwa", "159");
insert into rooms (id, room_name, city, street, number) values(322,"Dom z Ulicy Wiązów", "Katowice", "Ptysiowa", "13");
insert into rooms (id, room_name, city, street, number) values(323,"LCJescape", "Ruda Śląska", "Gazowa", "82");
insert into rooms (id, room_name, city, street, number) values(324,"Ministerstwo Szyfrów", "Ruda Śląska", "Stycznia", "41");
insert into rooms (id, room_name, city, street, number) values(325,"Piwnica Tajemnic", "Bytom", "Muzyczna", "217");
insert into rooms (id, room_name, city, street, number) values(326,"Escape Game Studio", "Katowice", "Kwiatowa", "180");
insert into rooms (id, room_name, city, street, number) values(327,"Time Is Up", "Ruda Śląska", "Chopina", "230");
insert into rooms (id, room_name, city, street, number) values(328,"Arena Zoltar Laser Tag & Escape Room's", "Bytom", "Rugego", "204");
insert into rooms (id, room_name, city, street, number) values(329,"Tkalnia Zagadek KIDS", "Katowice", "Skłodowskiej-Curie", "131");
insert into rooms (id, room_name, city, street, number) values(330,"Lock Ness Escape Room Rzeszów", "Kraków", "Projektowana", "130");
insert into rooms (id, room_name, city, street, number) values(331,"CODE - CENTRUM OD DOSTARCZANIA EMOCJI", "Gliwice", "Różana Droga", "45");
insert into rooms (id, room_name, city, street, number) values(332,"Escape Room Mrzeżyno", "Gliwice", "Bukowa", "121");
insert into rooms (id, room_name, city, street, number) values(333,"House Of Mystery", "Gliwice", "Aktorska", "128");
insert into rooms (id, room_name, city, street, number) values(334,"Escape ROOM Karpacz", "Kraków", "Pawia", "63");
insert into rooms (id, room_name, city, street, number) values(335,"Pokój Ucieczki Krokowa", "Ruda Śląska", "Orzechowa", "175");
insert into rooms (id, room_name, city, street, number) values(336,"Bastion Escape Room Zamość", "Ruda Śląska", "Akacjowa", "139");
insert into rooms (id, room_name, city, street, number) values(337,"Access Code Escape Room", "Kraków", "Kościelna", "47");
insert into rooms (id, room_name, city, street, number) values(338,"Mobilny Escape Room", "Ruda Śląska", "Listopada", "165");
insert into rooms (id, room_name, city, street, number) values(339,"Frantic Escape Room", "Bytom", "Wysockiego", "108");
insert into rooms (id, room_name, city, street, number) values(340,"Po Nitce Do Kłębka", "Katowice", "Białowieska", "213");
insert into rooms (id, room_name, city, street, number) values(341,"Imaginarium", "Bytom", "Młodzieży", "76");
insert into rooms (id, room_name, city, street, number) values(342,"The Great Escape", "Ruda Śląska", "Przedmiejska", "201");
insert into rooms (id, room_name, city, street, number) values(343,"Room 404", "Katowice", "Pilecka", "195");
insert into rooms (id, room_name, city, street, number) values(344,"Tajemnicza Kraina", "Katowice", "Szmaragdowych Żuków", "222");
insert into rooms (id, room_name, city, street, number) values(345,"Szyfrownia", "Ruda Śląska", "Serdeczna", "175");
insert into rooms (id, room_name, city, street, number) values(346,"King of the Lock", "Bytom", "Kościelna", "202");
insert into rooms (id, room_name, city, street, number) values(347,"Zoltar Park Kraków", "Bytom", "Muszera", "144");
insert into rooms (id, room_name, city, street, number) values(348,"AWAY OUT", "Ruda Śląska", "Rodzinna", "30");
insert into rooms (id, room_name, city, street, number) values(349,"Odległa Galaktyka", "Ruda Śląska", "Łowicka", "218");
insert into rooms (id, room_name, city, street, number) values(350,"Clue Room Poznań", "Bytom", "Koźlica", "174");
insert into rooms (id, room_name, city, street, number) values(351,"Ucieczka z Twierdzy", "Katowice", "Sosnowa", "104");
insert into rooms (id, room_name, city, street, number) values(352,"3xit", "Katowice", "Wiejska", "250");
insert into rooms (id, room_name, city, street, number) values(353,"Escape Us", "Katowice", "Kościelna", "185");
insert into rooms (id, room_name, city, street, number) values(354,"GameOver Escape", "Gliwice", "Kwiatowa", "42");
insert into rooms (id, room_name, city, street, number) values(355,"Projekt Escape", "Bytom", "Irysowa", "2");
insert into rooms (id, room_name, city, street, number) values(356,"C-Lock Stories", "Ruda Śląska", "Tylna", "120");
insert into rooms (id, room_name, city, street, number) values(357,"Kordero", "Gliwice", "Witosa", "11");
insert into rooms (id, room_name, city, street, number) values(358,"Save State", "Ruda Śląska", "Przyrodnicza", "13");
insert into rooms (id, room_name, city, street, number) values(359,"Enigma House", "Katowice", "Oliwkowa", "205");
insert into rooms (id, room_name, city, street, number) values(360,"Escape Lębork", "Kraków", "Wybickiego", "132");
insert into rooms (id, room_name, city, street, number) values(361,"LOCKED IN Escape Room", "Ruda Śląska", "Albańska", "81");
insert into rooms (id, room_name, city, street, number) values(362,"Inny Wymiar 1871", "Ruda Śląska", "Wyspiańskiego", "152");
insert into rooms (id, room_name, city, street, number) values(363,"Konsorcjum Czasu", "Bytom", "Luksemburg", "200");

